### ISSUE TITLE
Throws error with ansible-core >= 2.14

### ISSUE THREAD

**Issue by fbartusch** [ansible-middleware/ansible_collections_jcliff#89]
##### SUMMARY

Playbook fails when using jcliff collection with ansible >= 2.14

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.14.2
```

##### COLLECTION VERSION

```
0.0.23
```

##### STEPS TO REPRODUCE

Run a playbook that uses jcliff

```yaml
---
- hosts: <your host>

  roles:
  - jcliff
```

##### EXPECTED RESULTS

Running the playbook without errorrs.

##### ACTUAL RESULTS

```
TASK [middleware_automation.jcliff.jcliff : Test if package jcliff is already installed] **************************************************************************************************************************
fatal: [xxxxxxxxx]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}
```

This is because of the changes in ansible-core, that removed the `warn` parameter for `shell`
See: https://stackoverflow.com/a/74560322

That parameter is [used here](https://github.com/ansible-middleware/ansible_collections_jcliff/blob/main/roles/jcliff/tasks/install_rpm.yml#L21)

**Comment by rpelisse** [comment]
Hi, 

Thanks for the report, however, we might not come around investigating it any time soon. JCliff is more/less legacy code, since Wildfly now includes a YAML configuration feature, we uses this, through the [Wildfly collection](github.com/ansible-middleware/wildfly/), to configure the server (it's faster, cleaner and easier this way).

We'll be happy to review and merge a fix, plus trigger a release, however.

**Comment by fbartusch** [comment]
Hi,

thanks for suggesting the wildfly collection YAML configuration feature. I was able to change my configuration with it. It really makes the playbook shorter and is more convenient.
